// templates/vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import viteLogoUrl from './assets/vite.svg'
import vueLogoUrl from './assets/vue.svg'

const count = ref(0)
</script>

<template>
  <div
    class="flex flex-col gap-4 p-8 text-center rounded-2xl flex justify-center items-center fixed bottom-[70px] right-5 bg-black border! border-[#5384ed] border-solid"
  >
    <div class="flex items-center gap-4">
      <a href="https://vite.dev" target="_blank">
        <img :src="viteLogoUrl" alt="Vite logo" />
      </a>
      <span class="text-2xl font-bold">+</span>
      <a href="https://vuejs.org/" target="_blank">
        <img :src="vueLogoUrl" alt="Vue logo" />
      </a>
    </div>
    <button
      class="counter rounded-lg border! border-solid border-[#3e3e3e] px-5! py-2.5! text-base text-white font-medium font-inherit bg-[#1a1a1a] cursor-pointer transition-colors duration-250 hover:text-[#5384ed]! hover:border-[#5384ed]! border-solid"
      @click="count++"
    >
      {{ count }}
    </button>
  </div>
</template>

<style scoped></style>

// packages/media-peek/src/App.tsx
import { monkeyWindow } from '$'

import ReactSVG from '@/assets/react.svg'
import CountBtn from '@/components/count-btn'
import { Badge } from '@/components/ui/badge'

import { ThemeProvider } from './components/theme-provider'

function App() {
  console.log(window, 'App', monkeyWindow)
  console.log('parent', monkeyWindow.parent)
  // GM_addElement(document.body, 'div', { textContent: 'hello' })
  return (
    <ThemeProvider defaultTheme="system" storageKey="vite-ui-theme">
      <main className="fixed right-0 top-0 flex flex-col items-center justify-center h-24 bg-red-500 z-[9999]">
        <div className="flex flex-col items-center gap-y-4">
          <div className="inline-flex items-center gap-x-4">
            <img src={ReactSVG} alt="React Logo" className="w-32" />
            <span className="text-6xl">+</span>
            <img src={'/vite.svg'} alt="Vite Logo" className="w-32" />
          </div>
          <a href="https://ui.shadcn.com" rel="noopener noreferrer nofollow" target="_blank">
            <Badge variant="outline">shadcn/ui</Badge>
          </a>
          <CountBtn />
        </div>
      </main>
    </ThemeProvider>
  )
}

export default App
